### ISSUE TITLE
Is there a reason for the '@' symbol when adding keys to the dictionary?

### ISSUE THREAD

**Issue by jmb** [knipknap/Gelatin#25]
https://github.com/knipknap/Gelatin/blob/d2afa85a48034d6ee34580e49e16542f31ad208e/Gelatin/generator/Builder.py#L109

This means my output JSON has @ symbols in front of all the keys.

**Comment by knipknap** [comment]
The reason is that this makes it compatible with XML. For example, in XML a node can have both, a name attribute and a name child. A Gelatin file specifying both would cause broken output if were used to generate JSON.

If all you want is JSON output, don't use any Gelatin syntax that creates attributes; create node children instead.
